// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using dataAccess;

#nullable disable

namespace dataAccess.Migrations
{
    [DbContext(typeof(WindmillDbContext))]
    [Migration("20260225131934_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("dataAccess.Entities.Alert", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("FarmId")
                        .HasColumnType("uuid");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("Ts")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TurbineId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("FarmId", "Ts");

                    b.HasIndex("FarmId", "Severity", "Ts");

                    b.HasIndex("FarmId", "TurbineId", "Ts");

                    b.ToTable("alert", (string)null);
                });

            modelBuilder.Entity("dataAccess.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("app_user", (string)null);
                });

            modelBuilder.Entity("dataAccess.Entities.Farm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("farm", (string)null);
                });

            modelBuilder.Entity("dataAccess.Entities.OperatorAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("FarmId")
                        .HasColumnType("uuid");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("TurbineId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("ValidationError")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "RequestedAt");

                    b.HasIndex("FarmId", "TurbineId", "RequestedAt");

                    b.ToTable("operator_action", (string)null);
                });

            modelBuilder.Entity("dataAccess.Entities.TelemetryRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double?>("AmbientTemperature")
                        .HasColumnType("double precision");

                    b.Property<double?>("BladePitch")
                        .HasColumnType("double precision");

                    b.Property<Guid>("FarmId")
                        .HasColumnType("uuid");

                    b.Property<double?>("GearboxTemp")
                        .HasColumnType("double precision");

                    b.Property<double?>("GeneratorTemp")
                        .HasColumnType("double precision");

                    b.Property<double?>("NacelleDirection")
                        .HasColumnType("double precision");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<double?>("PowerOutput")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("RotorSpeed")
                        .HasColumnType("double precision");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Ts")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TurbineId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<double?>("Vibration")
                        .HasColumnType("double precision");

                    b.Property<double?>("WindDirection")
                        .HasColumnType("double precision");

                    b.Property<double?>("WindSpeed")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("FarmId", "Ts");

                    b.HasIndex("FarmId", "TurbineId", "Ts");

                    b.ToTable("telemetry", (string)null);
                });

            modelBuilder.Entity("dataAccess.Entities.Turbine", b =>
                {
                    b.Property<Guid>("FarmId")
                        .HasColumnType("uuid");

                    b.Property<string>("TurbineId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("FarmId", "TurbineId");

                    b.HasIndex("FarmId");

                    b.ToTable("turbine", (string)null);
                });

            modelBuilder.Entity("dataAccess.Entities.Alert", b =>
                {
                    b.HasOne("dataAccess.Entities.Farm", "Farm")
                        .WithMany("Alerts")
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dataAccess.Entities.Turbine", "Turbine")
                        .WithMany("Alerts")
                        .HasForeignKey("FarmId", "TurbineId");

                    b.Navigation("Farm");

                    b.Navigation("Turbine");
                });

            modelBuilder.Entity("dataAccess.Entities.OperatorAction", b =>
                {
                    b.HasOne("dataAccess.Entities.AppUser", "User")
                        .WithMany("OperatorActions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("dataAccess.Entities.Turbine", "Turbine")
                        .WithMany("OperatorActions")
                        .HasForeignKey("FarmId", "TurbineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Turbine");

                    b.Navigation("User");
                });

            modelBuilder.Entity("dataAccess.Entities.TelemetryRecord", b =>
                {
                    b.HasOne("dataAccess.Entities.Turbine", "Turbine")
                        .WithMany("Telemetry")
                        .HasForeignKey("FarmId", "TurbineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Turbine");
                });

            modelBuilder.Entity("dataAccess.Entities.Turbine", b =>
                {
                    b.HasOne("dataAccess.Entities.Farm", "Farm")
                        .WithMany("Turbines")
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Farm");
                });

            modelBuilder.Entity("dataAccess.Entities.AppUser", b =>
                {
                    b.Navigation("OperatorActions");
                });

            modelBuilder.Entity("dataAccess.Entities.Farm", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("Turbines");
                });

            modelBuilder.Entity("dataAccess.Entities.Turbine", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("OperatorActions");

                    b.Navigation("Telemetry");
                });
#pragma warning restore 612, 618
        }
    }
}
